project:
  type: website
  output-dir: _site
  resources:
    - assets/media

website:
  title: "Jimmy Cloutier"
  site-url: "https://www.jrcloutier.com"
  description: "Data and Investigative Journalist at the Pittsburgh Post-Gazette"
  navbar:
    right:
      - text: "About"
        href: pages/about.qmd
      - text: "Blog"
        href: blog/index.qmd
  search: false
  page-footer:
    left: >-
     &#169; 2025 Jimmy Cloutier &#8729; Made with [Quarto](https://quarto.org)

format:
  html:
    theme:
      - default
      - brand.yaml
    css: /assets/index.css
    code-link: false
    pagetitle: "{{< meta title >}}"
    lightbox: true
    include-in-header: assets/soundcite-head.html
    anchor-sections: false

execute:
  freeze: auto


