project:
  type: website
  output-dir: _site
website:
  title: "Jimmy Cloutier"
  site-url: https://jcloutier.com
  description: "Data and Investigative Journalist at the Pittsburgh Post-Gazette"
  navbar:
    right:
      - text: "About"
        href: pages/about.qmd
  page-footer:
    left: >-
     &#169; 2024 Jimmy Cloutier &#8729; Made with [Quarto](https://quarto.org)
format:
  html:
    theme:
      - default
      - brand.yaml
    css: assets/index.css
    code-link: false
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute:
  freeze: auto
